apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-server
  name: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-server
    spec:
      containers:
        - image: nginx:latest
          name: nginx-server
          ports:
            - containerPort: 8080
            - containerPort: 443
          resources: {}
      restartPolicy: Always
status: {}
