# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose --file docker-compose-djangohelloworld.yaml convert -c
#     kompose.version: 1.24.0 (4a2a0458)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: redis
#   name: redis
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: redis
#   strategy: {}
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose --file docker-compose-djangohelloworld.yaml convert -c
#         kompose.version: 1.24.0 (4a2a0458)
#       creationTimestamp: null
#       labels:
#         io.kompose.service: redis
#     spec:
#       containers:
#         - image: redis:latest
#           name: redis
#           resources: {}

#           args: ["--requirepass", "${DB_PASS}"]
#           envFrom:
#           - secretRef:
#               name: mysecret

#           ports:
#             - containerPort: 6379

#       restartPolicy: Always
# status: {}





---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image: redis:latest

        args: ["--requirepass", "$(DB_PASS)"]

        envFrom:
        - secretRef:
            name: mysecret

        ports:
        - containerPort: 6379
