apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-djangohelloworld.yaml convert -c
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-server
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-djangohelloworld.yaml convert -c
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-server
    spec:
      containers:
        - args:
            - --requirepass
          image: redis:latest
          name: redis-server
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
