# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: kompose --file docker-compose-djangohelloworld.yaml convert -c
#     kompose.version: 1.24.0 (4a2a0458)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: redis
#   name: redis
# spec:
#   ports:
#     - name: "6379"
#       port: 6379
#       targetPort: 6379
#   selector:
#     io.kompose.service: redis
# status:
#   loadBalancer: {}








# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: django-app
#   labels:
#     app: django
# spec:
#   selector:
#     app: django
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-server
#   labels:
#     app: redis-server
# spec:
#   selector:
#     app: redis
#   ports:
#     - protocol: TCP
#       port: 6379
#       targetPort: 6379






apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-server
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379





















